<link rel="shortcut icon" href="{{asset("assets/images/logo/favourite_icon.png")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/bootstrap.min.css")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/fontawesome.css")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/aos.css")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/animate.css")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/slick.css")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/slick-theme.css")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/magnific-popup.css")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/nice-select.css")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/jquery-ui.css")}}">
<link rel="stylesheet" type="text/css" href="{{asset("assets/css/style.css")}}">
